[workspace]
resolver = "2"

members = [
    "framework",
    "aoc_*",
]
default-members = ["aoc_2023"]

[workspace.dependencies]
ahash = "0.8"
anyhow = "1"
bitvec = "1.0.1"
clap = { version = "4", features = ["color", "derive"]}
colored = "2.0.0"
criterion = { version = "0.4", features = ["html_reports"] }
divan = "0.1.4"
framework = { path = "./framework" }
glam = "0.24.2"
hex = "0.4.3"
itertools = "0.10"
lending-iterator = "0.1.7"
miette = { version = "5.10", features = ["fancy"] }
ndarray = "0.15.6"
nom = "7.1.3"
nom-supreme = "0.8.0"
nom_locate = "4.2.0"
pathfinding = "4.6.0"
petgraph = "0.6.4"
rstest = "0.18.2"
rstest_reuse = "0.6.0"
test-log = { version = "0.2.13", default-features = false, features = [
    "trace",
] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["fmt", "env-filter"] }
z3 = {version="0.12", features = []}

[profile.release]
debug = true

[profile.dev]
opt-level = 1               # Use slightly better optimizations.
