[workspace]
members = [
    "framework",
    "aoc_*",
]

default-members = ["aoc_2023"]

[profile.release]
debug = true

[profile.dev]
opt-level = 1               # Use slightly better optimizations.
