[workspace]
members = [
    "framework",
    "aoc_2020",
    "aoc_2021",
    "aoc_2022",
]

default-members = ["aoc_2022"]

[profile.release]
debug = true

[profile.dev]
opt-level = 1               # Use slightly better optimizations.
