[package]
name = "aoc_2024"
version = "1.0.0"
edition = "2021"

[dependencies]
aoc_lib = { workspace = true }
common = { workspace = true }
indoc = { workspace = true }
itertools = { workspace = true }
miette = { workspace = true }
nom = { workspace = true }
