[package]
name = "aoc_2024"
version = "1.0.0"
edition = "2021"
license = "MIT"

[dependencies]
aoc-runner = { path = "../aoc-runner" }
aoc-runner-macros = { path = "../aoc-runner-macros" }
glam.workspace = true
itertools.workspace = true
nom.workspace = true
tracing.workspace = true
