[package]
name = "aoc2023"
version = "1.0.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
bitvec = "1.0.1"
clap = { workspace = true }
framework = { workspace = true }
glam = { workspace = true }
hex = "0.4.3"
itertools = { workspace = true }
nom = { workspace = true }
nom-supreme = { workspace = true }
nom_locate = { workspace = true }
petgraph = "0.6.4"
rstest = { workspace = true }
rstest_reuse = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
