[package]
name = "framework"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8"
anyhow = "1"
#bitvec = "1.0.1"
colored = "2"
clap = { version = "4", features = ["color", "derive"]}
thiserror = "1"
ureq = "2"
