[package]
name = "framework"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.2"
anyhow = "1.0.66"
colored = "2.0"
#chrono = "0.4"
#colored = "2.0"
#clap = { version = "4", features = ["color", "derive"]}
reqwest = { version = "0.11", features = ["blocking"] }
thiserror = "1.0"
ureq = "2.5"
