[package]
name = "framework"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8"
anyhow = "1"
colored = "2"
clap = { version = "4", features = ["color", "derive"] }
thiserror = "1"
ureq = "2"
itertools = "0.10.5"
chrono = "0.4.31"
nom = "7.1.3"
nom-supreme = "0.8.0"
