name: aoc_2024
on:
  workflow_dispatch:
  push:
    paths:
      - "common/**"
      - "framework/**"
      - "aoc_2024/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: build/test
        run: nix build .#aoc-2024-test -Lv
      - name: ls
        run: ls -la result/
