name: aoc_2024
on:
  workflow_dispatch:
  push:
    paths:
      - "common/**"
      - "framework/**"
      - "aoc_2024/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: polarmutex
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: build/test
        run: nix build .#aoc-2024-test -L
      - name: ls
        run: ls -la result/
